name: CI-CD

on:
  push:
    branches: ["main"]
    
jobs:
  CI: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Construcao da imagem docker
      uses: docker/build-push-action@v5.1.0
      with: 
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          davescott99/astfx-discserv:v1.1-a
          davescott99/astfx-discserv:latest
          
        
