name: CI-CD

on:
  push:
    branches: ["main"]
    
jobs:
  CI: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Autenticacao no Docker Hub
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      with: 
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PWD}}
        
    - name: Construcao da imagem Docker
      uses: docker/build-push-action@v5.1.0
      with: 
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          davescott99/astfx-discserv:v1.1-a
          davescott99/astfx-discserv:latest
          
        
